// build.js
// ----------------------------------------------------------------------------
// Bundles the ES modules under public/ into a single self-contained HTML
// file (`cdse.html`) that opens via double-click on Windows / macOS — no
// local web server needed.
//
// Why this exists: browsers block ES-module imports from `file://` URLs for
// security reasons, so the modular `index.html` only renders when served
// over HTTP. The build inlines all our JS into one <script> tag wrapped in
// an IIFE, sidestepping the issue while keeping `public/*.js` editable.
//
// Run:   node build.js
// ----------------------------------------------------------------------------

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const PUB = path.join(ROOT, 'public');

// Module concatenation order — leaves first, then dependents.
const ORDER = [
  'fields.js',
  'presets.js',
  'query-engine.js',
  'repository.js',
  'app.js',
];

function readModule(filename) {
  let code = fs.readFileSync(path.join(PUB, filename), 'utf-8');

  // Strip `import ... from '...';` lines (potentially multi-line)
  code = code.replace(/import[\s\S]*?from\s*['"][^'"]+['"]\s*;?/g, '');

  // Strip `export default ` prefix
  code = code.replace(/\bexport\s+default\s+/g, '');

  // Drop the `export` keyword before declarations
  code = code.replace(/\bexport\s+(?=class|function|async\s+function|const|let|var)/g, '');

  // Drop bare `export { ... };` re-exports
  code = code.replace(/\bexport\s*\{[^}]*\}\s*;?/g, '');

  return code.trim();
}

// Build tag: short ISO timestamp, visible in the sidebar so users can
// confirm at a glance which build is loaded.
const buildTag = new Date().toISOString().replace(/[-:]/g, '').slice(2, 13); // YYMMDDTHHMM

let bundle = ORDER.map((f) => `/* ===== public/${f} ===== */\n${readModule(f)}`).join('\n\n');
bundle = bundle.replace(/__BUILD_TAG__/g, buildTag);

const wrappedScript = `<script>\n(function () {\n"use strict";\n${bundle}\n})();\n</script>`;

// Read index.html and replace the module loader with the inline bundle.
const indexPath = path.join(ROOT, 'index.html');
let html = fs.readFileSync(indexPath, 'utf-8');

let replaced = html.replace(
  /<script\s+type="module"\s+src=["']\.\/public\/app\.js["']\s*><\/script>/,
  wrappedScript,
);

if (replaced === html) {
  console.error('ERROR: could not find the module script tag to replace.');
  process.exit(1);
}

// Inline Chart.js, Alpine.js and a statically-compiled Tailwind stylesheet.
// CDN access can be blocked by corporate firewalls or by the browser's
// file:// security context, leaving the page unstyled or chartless with
// no visible error. Everything important ships in the file now.
function inlineScript(srcPath, label) {
  const code = fs.readFileSync(path.join(PUB, 'vendor', srcPath), 'utf-8');
  return `<script>/* ${label} (inlined) */\n${code}\n</script>`;
}
function inlineStyle(srcPath, label) {
  const code = fs.readFileSync(path.join(PUB, 'vendor', srcPath), 'utf-8');
  return `<style>/* ${label} (inlined) */\n${code}\n</style>`;
}

replaced = replaced.replace(
  /<script\s+src="https:\/\/cdn\.jsdelivr\.net\/npm\/chart\.js[^"]+"\s*><\/script>/,
  inlineScript('chart.umd.js', 'Chart.js 4.4.4'),
);

replaced = replaced.replace(
  /<script\s+defer\s+src="https:\/\/cdn\.jsdelivr\.net\/npm\/alpinejs[^"]+"\s*><\/script>/,
  inlineScript('alpine.min.js', 'Alpine.js 3.14.1'),
);

// Replace the Tailwind play CDN + inline config with the precompiled CSS.
// One regex consumes both the loader and the tailwind.config script that
// follows it, so the output HTML has neither.
replaced = replaced.replace(
  /<script\s+src="https:\/\/cdn\.tailwindcss\.com"\s*><\/script>\s*<script>[\s\S]*?tailwind\.config[\s\S]*?<\/script>/,
  inlineStyle('tailwind.compiled.css', 'Tailwind CSS (compiled from tailwind.config.cjs)'),
);

// Add a small "generated, do not edit" banner at the top of the file
const banner = `<!-- Generated by build.js — single-file build of index.html + public/*.js
     Edit the sources, then run: node build.js -->\n`;
const out = replaced.replace(/<!DOCTYPE html>/, `<!DOCTYPE html>\n${banner}`);

const outPath = path.join(ROOT, 'cdse.html');
fs.writeFileSync(outPath, out);

const sizeKB = (Buffer.byteLength(out) / 1024).toFixed(1);
console.log(`✓ cdse.html written (${sizeKB} KB) · build ${buildTag}`);
